### ISSUE TITLE
Eingabe der Kategorie-Farben

### ISSUE THREAD

**Issue by DanielWeitenauer** [FriendsOfREDAXO/sked#100]
RGB(a)-Farbwerte aus den Einstellungen werden nur zur Auswahl angeboten, wenn die Werte in den Klammern ohne Leerzeichen eingegeben werden.

**Comment by joachimdoerr** [comment]
Ich finde das ist jetzt eher weniger ein Bug.

**Comment by eaCe** [comment]
Kein Bug, aber verwirrende UX. Da ich gerade daran arbeite könnte ich einfach die Leerzeichen entfernen. Sicher nicht elegant aber funktioniert...

preg_match_all("((#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3}))|(rgba|rgb)\(\s*(?:(\d{1,3})\s*,?){3}(1|0?\.\d+)\))",str_replace(' ', '', $this->getConfig('sked_colors')), $matches);

Wenn das gewollt ist werfe ich das noch mit in den kommenden PR

**Comment by skerbis** [comment]
👍

**Comment by skerbis** [comment]
Danke @eaCe
