### ISSUE TITLE
DatePicker überschreibt Datum

### ISSUE THREAD

**Issue by claudihey** [FriendsOfREDAXO/sked#103]
Beim Editieren des von-Datums wird das bis-Datum überschrieben, umgekehrt die gleiche Situation. Dadurch ist es nicht möglich, eine Zeitspanne einzugeben. Manuelle Eingabe funktioniert allerdings.

**Comment by skerbis** [comment]
Das liegt daran, dass immer beide Felder mit dem Dicker bearbeitet werden. Eigentlich reicht hier ein Datumspicker.  Es ist unschön, aber kein Fehler.

**Comment by claudihey** [comment]
Ah, okay... Wenn man es weiß, leuchtet es auch ein... Nur der Kunde und ich haben es beide nicht kapiert... Vielleicht kann man noch einen kleinen Hinweis dazu schreiben?
