### ISSUE TITLE
Wozu das M im Addonname?

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/sked#11]
Ich fände es gut, wenn wir bei FoR auf diese Prefixe verzichten können.

**Comment by joachimdoerr** [comment]
Hast du eine Idee für ein alternativen Name? Mir persönlich ist das total egal, bin halt was Namensfindung für Addons angehet eher untalentiert.

**Comment by skerbis** [comment]
Meine Namensvorschläge, da es mehr ist als einfach "nur" ein Kalender 

- CalendarGen
- CalGenerator
- CalGen
- ProCal
- CalPro
- UltimateCal
- Clndr
- MyCal 
... hehe und iCal ... weil individuell ;-)

**Comment by joachimdoerr** [comment]
@skerbis mit iCal würd A mich ganz sicher verklagen aber `eiCal` würd sicher gehen...

**Comment by skerbis** [comment]
Sonst einfach Calendar

**Comment by schuer** [comment]
`calendar` ist belegt. Aber wie wär’s mit `kalender`?
Ansonsten: `events` scheint frei.

**Comment by skerbis** [comment]
events finde ich nicht so gut, da es direkt eine Funktion festlegt. Dieser Kalender kann aber mehr als nur "Events". Er ist wegen der individuellen Felder eher ein Generator.

**Comment by skerbis** [comment]
Was hält ihr von Sked?
https://en.wikipedia.org/wiki/Sked

**Comment by joachimdoerr** [comment]
Sked gefällt mir.
