### ISSUE TITLE
Löschung Termine

### ISSUE THREAD

**Issue by fw-thomas** [FriendsOfREDAXO/sked#111]
Guten Morgen,
gibt es die Planung, das veraltete Termine sich von selber löschen ?? 

Oder habe ihr eine Idee wie man 2 Seiten mit Terminen am einfachsten Löschen kann ?

mfg
thomas

**Comment by skerbis** [comment]
cronjob anlegen und die Daten per sql entsprechend Deiner Bedingungen löschen.

**Comment by skerbis** [comment]
Am besten du fragst mal im Forum oder Slack-Channel, ob dir dabei jemand helfen kann.
