### ISSUE TITLE
Kalenderblatt drucken

### ISSUE THREAD

**Issue by fw-thomas** [FriendsOfREDAXO/sked#112]
hallo zusammen,
gibt es die Möglichkeit den Kalender auszudrucken .. 

mfg
thomas

**Comment by skerbis** [comment]
Eine entsprechende Ausgabe musst du selbst realisieren. Sked liefert keine fertigen Ausgaben für das Frontend. Es ist mehr oder weniger wie yform ein Generator / Editor mit Verwaltung
