### ISSUE TITLE
Feld uid den Entries hinzufügen

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/sked#119]
Beim Import aus externen Kalendersystemen gibt es meist eine eindeutige ID, mit deren Hilfe man beim Update bestehende Datensätze zuordnen kann. Es wäre daher hilfreich, wenn Sked von Haus aus ein zusätzliches Feld in der DB anbietet und(!) UNIQUE setzt, da das id-Feld oder ein custom-Feld hierfür nicht ausreicht.

Mit dem uid-unique-Feld kann ich bspw. direkt die Methode insertOrUpdate() der rex_sql-Klasse nutzen.

Dazu würde es ausreichnen, beim Installieren/Updaten ein UID-Feld wie folgt zu definieren.

```
rex_sql_table::get(rex::getTable('sked_entries'))
    ->ensureColumn(new rex_sql_column('id', 'int(11) unsigned', false, null, 'auto_increment'))
    ->ensureColumn(new rex_sql_column('uid', 'varchar(192)'))

[...]

    ->setPrimaryKey('id')
    ->ensureIndex(new rex_sql_index('uid', ['uid'], rex_sql_index::UNIQUE))
    ->ensure();
```

**Comment by skerbis** [comment]
gerne PR @alexplusde

**Comment by joachimdoerr** [comment]
1c0164f73d7a9b1c8a8bcc2e884f3bd17120434f
