### ISSUE TITLE
Ausgabe von Structured Data / JSON-LD events / ICAL

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/sked#12]
https://developers.google.com/search/docs/data-types/events

**Comment by skerbis** [comment]
Sehe ich nicht als Aufgabe des Kalenders an. Ist eher eine Sache des wenigen der die Ausgabe des Kalenders erstellt. (Modul etc.)

**Comment by alexplusde** [comment]
Schade, hätte ich als Out-of-the-Box-Lösung gut gefunden.

**Comment by skerbis** [comment]
Sicher. Allerdings ist machender mehr oder weniger ein Generator, der leicht durch weitere Felder ergänzt werden kann. Diese Daten möchte man evtl. nicht alle in der JSON-LD. Mcalender müsste alle individuellen Felder und Ausschlüsse beachten.  Nach JSON-LD möchte man etl. auch ne .ics ausgeben usw.. Es wäre sinnvoller hierfür zentrale Klassen und Funktionen zu hinterlegen, die Daten aus beliebigen Quellen (auch andere Addons) annehmen können und dann die Ausgabe dafür erstellen.

**Comment by joachimdoerr** [comment]
Da kann ich mir ein Plugin vorstellen

**Comment by alexplusde** [comment]
Für ICS
https://github.com/jasvrcek/ICS

**Comment by skerbis** [comment]
ICS kann selbst leicht realisiert werden. JSON steht über die API jetzt zur Verfügung. Vorerst close.

**Comment by alexplusde** [comment]
Ist für mich dann Teil der Doku, deswegen mache ich es wieder auf.

**Comment by alexplusde** [comment]
Ich werde eine Lösung schaffen
https://github.com/alexplusde/sked_ics/

Beteiligung erwünscht.

**Comment by joachimdoerr** [comment]
wie gesagt ich würde soetwas als plugin sehen: https://jsonld.com/event/ (thanks @skerbis für den link) -> das mapping sollte ja kein großes problem sein.

**Comment by alexplusde** [comment]
Ich schieb' das später gerne zu FOR in das Repo als Plugin, aber ich bin noch nicht soweit.

**Comment by skerbis** [comment]
hier tut sich nix. Wenn doch, wieder aufmachen.
