### ISSUE TITLE
Sortierung nach Uhrzeit innerhalb eines Tages 

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/sked#126]
Es scheint eine Sortierung nach der Uhrzeit zu fehlen. Bzw. kann ich die irgendwie beeinflussen?

@joachimdoerr 

![bildschirmfoto 2019-03-08 um 11 40 43](https://user-images.githubusercontent.com/791247/54024185-48dfbb80-4197-11e9-8fee-85a352ecc4e7.png)

**Comment by joachimdoerr** [comment]
f749574057b458d788f2025c440893946c7d4c54
