### ISSUE TITLE
wiederkehrendes Ereignis: zusätzliche Option -> täglich

### ISSUE THREAD

**Issue by isospin** [FriendsOfREDAXO/sked#128]
z.Zt. gibt es bei den wiederkehrenden Ereignissen die Optionen: 
```
- wöchentlich
- monatlich
- jährlich
```
eine zusätzliche option
`- täglich `
wäre super

**Comment by skerbis** [comment]
gerne wieder aufmachen, wenn jemand einen PR einreichen möchte.
