### ISSUE TITLE
Unterkategorien?

### ISSUE THREAD

**Issue by ansichtsache** [FriendsOfREDAXO/sked#131]
Wäre eine Erweiterung der Kategorien um Unterkategorien möglich?
(z.B. Kategorie 'Sprachkurse' mit Unterkategorien Englisch/Spanisch/Schwedisch/Portugisisch/etc.?)

**Comment by skerbis** [comment]
Man sollte die Kategorien als einzelne Kalender verstehen. 
Du kannst aber Rubriken und Kategorien über zusätzliche Felder ( pflegbar z.B. über yform) hinzufügen.
