### ISSUE TITLE
Fehler

### ISSUE THREAD

**Issue by simonsinus** [FriendsOfREDAXO/sked#132]
Hallo zusammen,

ich habe immernoch einen Error, wenn ich ein Termin anlegen will:

Liegts am Server?

Error thrown with message "Call to a member function setAttribute() on null"

Stacktrace:
#10 Error in /var/www/vhosts/hosting7950.af933.netcup.net/httpdocs/redaxo/src/addons/sked/pages/entries.php:487
#9 include in /var/www/vhosts/hosting7950.af933.netcup.net/httpdocs/redaxo/src/core/lib/packages/package.php:228
#8 rex_package:includeFile in /var/www/vhosts/hosting7950.af933.netcup.net/httpdocs/redaxo/src/core/lib/be/controller.php:474
#7 rex_be_controller:includePath in /var/www/vhosts/hosting7950.af933.netcup.net/httpdocs/redaxo/src/core/lib/be/controller.php:430
#6 rex_be_controller:includeCurrentPageSubPath in /var/www/vhosts/hosting7950.af933.netcup.net/httpdocs/redaxo/src/addons/sked/pages/index.php:10
#5 include in /var/www/vhosts/hosting7950.af933.netcup.net/httpdocs/redaxo/src/core/lib/packages/package.php:228
#4 rex_package:includeFile in /var/www/vhosts/hosting7950.af933.netcup.net/httpdocs/redaxo/src/core/lib/be/controller.php:474
#3 rex_be_controller:includePath in /var/www/vhosts/hosting7950.af933.netcup.net/httpdocs/redaxo/src/core/lib/be/controller.php:413
#2 rex_be_controller:includeCurrentPage in /var/www/vhosts/hosting7950.af933.netcup.net/httpdocs/redaxo/src/core/backend.php:215
#1 require in /var/www/vhosts/hosting7950.af933.netcup.net/httpdocs/redaxo/src/core/boot.php:135
#0 require in /var/www/vhosts/hosting7950.af933.netcup.net/httpdocs/redaxo/index.php:9

MARKDOWN:

**Error:** Call to a member function setAttribute() on null
**File:** redaxo/src/addons/sked/pages/entries.php
**Line:** 487

<details>
<summary>Stacktrace</summary>

| Function                                     | File                                     | Line     |
| -------------------------------------------- | ---------------------------------------- | -------- |
| include                                      | redaxo/src/core/lib/packages/package.php | 228      |
| rex_package->includeFile                     | redaxo/src/core/lib/be/controller.php    | 474      |
| rex_be_controller::includePath               | redaxo/src/core/lib/be/controller.php    | 430      |
| rex_be_controller::includeCurrentPageSubPath | redaxo/src/addons/sked/pages/index.php   | 10       |
| include                                      | redaxo/src/core/lib/packages/package.php | 228      |
| rex_package->includeFile                     | redaxo/src/core/lib/be/controller.php    | 474      |
| rex_be_controller::includePath               | redaxo/src/core/lib/be/controller.php    | 413      |
| rex_be_controller::includeCurrentPage        | redaxo/src/core/backend.php              | 215      |
| require                                      | redaxo/src/core/boot.php                 | 135      |
| require                                      | redaxo/index.php                         | 9        |

</details>
<details>
<summary>System report (REDAXO 5.7.1, PHP 7.2.15)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.7.1      |

| PHP           |            |
| ------------: | :--------- |
|       Version | 7.2.15     |
|       OPcache | yes        |
|        Xdebug | no         |

| Database      |                        |
| ------------: | :--------------------- |
|       Version | 5.6.44                 |
| Character set | utf8 (utf8_general_ci) |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | cgi-fcgi   |
|     Webserver | Apache     |

| Request       |              |
| ------------: | :----------- |
|       Browser | Firefox/67.0 |
|      Protocol | HTTP/1.1     |
|         HTTPS | yes          |

| Packages          |             |
| ----------------: | :---------- |
|           adminer | 1.5.0       |
|            backup | 2.3.0       |
|       be_explorer | 1.0.0       |
|          be_style | 2.7.1       |
|   be_style/redaxo | 2.7.0       |
|           bloecks | 1.4.0       |
|  bloecks/cutncopy | 1.4.0       |
| bloecks/dragndrop | 1.4.0       |
|    bloecks/status | 1.4.0       |
|    cookie_consent | 3.0.0-beta3 |
|           cronjob | 2.4.1       |
|         developer | 3.8.0       |
|           install | 2.5.0       |
|     media_manager | 2.6.0       |
|         mediapool | 2.5.0       |
|          metainfo | 2.4.0       |
|       multiupload | 2.1.3       |
|         phpmailer | 2.5.1       |
|           project | dev         |
|              sked | 1.6.2       |
|         structure | 2.7.0       |
| structure/content | 2.7.0       |
|          tinymce4 | 1.2         |
|             users | 2.5.2       |
|             xcore | 1.1.3       |
|              ycom | 3.0-beta4   |
|         ycom/auth | 3.0-beta4   |
|         ycom/docs | 3.0-beta4   |
|        ycom/group | 3.0-beta4   |
|             yform | 3.1.1       |
|        yform/docs | 3.1.1       |
|       yform/email | 3.1.1       |
|     yform/manager | 3.1.1       |
|       yform/tools | 3.1.1       |
|          yrewrite | 2.5         |

</details>

**Comment by skerbis** [comment]
Immer noch @simonsinus ?
