### ISSUE TITLE
Cache in Cache-Ordner schreiben, nicht data-Ordner

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/sked#133]
ich schließe per `.gitignore` den Cache-Ordner aus, damit diese Daten nicht versioniert werden. Sked legt jedoch cache-Daten im Data-Ordner ab unter `/redax/data/addons/sked/definitions/.cache/...` - dort gehören sie nicht hin.

**Comment by skerbis** [comment]
kurz die definitions solltest du schon versionieren. Denn dort erstellst du ggf. deine custom definitions

**Comment by alexplusde** [comment]
Ich glaube, die beiden verlinkten Codezeilen sind nicht die, die geändert werden müssen.

**Comment by joachimdoerr** [comment]
dba9e8af958b5e1c419bc4af246648260f36a961

**Comment by alexplusde** [comment]
Danke!
