### ISSUE TITLE
Firefox: Fehler in der Kalenderübersicht (Cross-Origin)

### ISSUE THREAD

**Issue by ansichtsache** [FriendsOfREDAXO/sked#136]
Ich bekomme in der Kalenderübersicht im REX-Backend einen "Error:" und die Termine werden nicht angezeigt.
Fehler taucht aber bisher nur im Firefox auf, in Safari funktioniert es …

> Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://www.domain.tld/index.php?rex-api-call=sked_exchange…RsaE5m3CWzJXwt8DVDYZORBpiSck&start=2019-07-29&end=2019-09-09. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt).

REX 5.7.1, Sked 1.7.1

**Comment by skerbis** [comment]
Du versuchst über eine externe Adresse auf die API zuzugreifen?
Dann sollte Dir das hier helfen: https://developer.mozilla.org/de/docs/Web/HTTP/CORS/Errors/CORSFehltQuelleErlauben

**Comment by ansichtsache** [comment]
eigentlich nicht das ich wüsste … was immer da auch aufgerufen wurde, jetzt taucht der fehler nicht mehr auf. aber danke für den link. falls doch noch was ist.

**Comment by skerbis** [comment]
@ansichtsache Wechsel zwischen www und non-www

**Comment by ansichtsache** [comment]
nö

**Comment by alexplusde** [comment]
Bei mir war der Backend-Aufruf http und die Domain in den System-Einstellungen von REDAXO https. Wechsel zu https war erfolgreich. Kann man das abfangen?

**Comment by isospin** [comment]
bin ich gerade auch drüber gestolpert.

**Comment by skerbis** [comment]
@isospin hast du feststellen können woran es lag?

**Comment by isospin** [comment]
ja, es war wie bei alex. ich hab die domain mit https aufgerufen und in den systemeinstellungen war http eingetragen. der rex_api_call wurde geblockt...

**Comment by skerbis** [comment]
Ok. Das scheint ein Konfigurationsfehler zu sein. Der sich sich nicht auf sked bezieht - daher close

**Comment by alexplusde** [comment]
Ich finde nicht, dass man annehmen muss, dass dieses Verhalten ein Konfigurationsfehler ist. Vielleicht sollte man das aber im Core lösen.

**Comment by skerbis** [comment]
Aus meiner Sicht ist es ein Konfigurationsfehler. Ich sehe hier auch keine Möglichkeit was der Core da machen soll? Im System wurde ja anstelle https http eingegeben. Ganz klar ein Konfigurationsfehler.

**Comment by alexplusde** [comment]
Wenn man etwas doppelt einstellen kann, was mit einer Einstellung abgedeckt ist (einmal https in der config.yml einstellen, einmal https im System angeben), und das zu einem Fehler führt, dann ist das nicht optimal.

**Comment by skerbis** [comment]
Was ist mit yrewrite? Hier kann ich es ja auch nach Belieben eingeben und das ist gut so. Es kann sein dass eine Website auch unter http erreichbar sein muss (um einen Zugriff z.B. aus China zur ermöglichen)

**Comment by alexplusde** [comment]
In YRewrite hat das keine Auswirkung ums Backend-Verhalten.

**Comment by skerbis** [comment]
Bitte an anderer Stelle klären. Es ist kein Sked-Problem.
