### ISSUE TITLE
.ics Export

### ISSUE THREAD

**Issue by marcohanke** [FriendsOfREDAXO/sked#139]
Die Möglichkeit eine ics zu exportieren (oder noch besser einen ics Link bereitzustellen) wäre cool.

**Comment by eaCe** [comment]
Gibts das nicht von @alexplusde ? Siehe Sked ICS

**Comment by alexplusde** [comment]
Habe ich mal angefangen. Mach ich weiter gegen Beauftragung.

**Comment by skerbis** [comment]
Sonst @alexplusde würde sich sicher über einen PR freuen

**Comment by marcohanke** [comment]
@alexplusde saß gerade hier und wir haben das besprochen ...

**Comment by skerbis** [comment]
Mit der Spatie lib ist es nun möglich einzelne Termine als Link auszugeben.
