### ISSUE TITLE
Warum MySql 5.6.15?

### ISSUE THREAD

**Issue by tema-web** [FriendsOfREDAXO/sked#140]
Gibt es eine zwingenden Grund, dass MySQL auf min. 5.6.15 gesetzt wurde? 
Ich kann die aktuelle Version von Sked bei mehreren Hostern nicht installieren, da dort noch 5.5.5 läuft :(

**Comment by skerbis** [comment]
Weil wir Routinen verwenden, die in 5.5.5 nicht existieren. Zudem ist der Support von 5.5.5 längst beendet und sollte nicht mehr betrieben werden:https://endoflife.software/applications/databases/mysql
