### ISSUE TITLE
wiederkehrendes Ereigniss: zusätzliche Option -> jeden xten Wochentag im Monat

### ISSUE THREAD

**Issue by tema-web** [FriendsOfREDAXO/sked#141]
Die Möglichkeit z.B. jeden 1. Mittwoch im Monat als Option für wiederkehrende Ereignisse zu haben, wäre auch nicht schlecht.

**Comment by skerbis** [comment]
Wähle monatlich, dann den 1. Mittwoch, sollte klappen.

**Comment by tema-web** [comment]
Nope, der Eintrag wird immer an dem Datum im Monat wiederholt ... hab aber auch nur 1.7.2 laufen ;-)

**Comment by skerbis** [comment]
Ja mal schauen. Hat aber mit der Version nichts zu tun. Die Option gibt es (noch) nicht. 
PR oder Auftrag Welcome.

**Comment by joachimdoerr** [comment]
Das zöge dann noch weitere Wunschoptionen mit sich wie z.b. ein bestimmter Tag in der Woche oder jede zweite Woche oder jeder 3. Donnerstag im Monat.

**Comment by skerbis** [comment]
Ausser an ungeraden Freitagen ;-)

**Comment by skerbis** [comment]
Wird gemacht. @tema-web Über eine finanzielle Beteiligung würde ich mich freuen.

**Comment by tema-web** [comment]
Hi Thomas, ich würde dich ja gerne erfreuen. Schreib mir doch mal ne Mail an tito@tietz-munoz.de und sag mir, was dir so vorschwebt.

**Comment by joachimdoerr** [comment]
48a1f91e419718edc5fc9f1a87e20a55c92adcdf
