### ISSUE TITLE
Shortcuts und Einstellungen

### ISSUE THREAD

**Issue by eaCe** [FriendsOfREDAXO/sked#142]
Wäre es gewünscht shortcodes zu nutzen? Bei Artikeln wird SHIFT+A zum hinzufügen genutzt, weiter würde ich STRG+S zum speichern bevorzugen. 

Gerne würde ich auch die Einstellungen um die Option erweitern die Ganztägiges Ereignisse zu aktivieren bzw. deaktivieren. In meinem Falle ist ein ganztägiges Ereignis die Ausnahme.

Wenn ihr damit einverstanden wärt würde ich, sobald ich das ganze eingebaut habe, einen PR eröffnen.

**Comment by eaCe** [comment]
Und was mir noch einfällt, könnte man die Zeit im Enddatum auch default auf +X Stunden setzen?

**Comment by skerbis** [comment]
Hört sich gut an.  PR Welcome

**Comment by skerbis** [comment]
@eaCe  kommt hier noch was?

**Comment by eaCe** [comment]
Oha, lang ist's her. Ich schau das ich mir das im Februar zwischenquetsche!

**Comment by eaCe** [comment]
Habe die shortcuts hinzugefügt.
Funktioniert nun so wie in der Struktur oder in yForm. 
Es wird entweder immer ein Termin angelegt mit dem heutigen Tag, außer in der Tag-Ansicht, dort immer der aktuell gewählte Tag.

Der shortcut ist je nach Browser unterschiedlich, einige unterstützen das Anzeigen der Kombination z.B. Firefox:
![grafik](https://user-images.githubusercontent.com/2708231/107859413-88aa8580-6e39-11eb-885d-0b1d9c512671.png)
Weitere Informationen: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/accessKeyLabel

Das Speichern mit Strg+S/Ctrl+S ist optional einstellbar. 
Ebenso der voreingestellter Ganztägiger Termin (default vorausgewählt) 
![grafik](https://user-images.githubusercontent.com/2708231/107859552-8dbc0480-6e3a-11eb-9241-0179e38898b9.png)

Gerne testen, wenn es so passt öffne ich einen PR.

**Comment by skerbis** [comment]
👍

**Comment by eaCe** [comment]
Ist das nun ein - Ja machen wir so - oder soll ich den PR erstellen? :)

**Comment by skerbis** [comment]
Gerne den PR erstellen 😀

**Comment by skerbis** [comment]
Danke @eaCe
