### ISSUE TITLE
Verkehrte Sprache / Datumsformat im datepicker

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/sked#144]
![image](https://user-images.githubusercontent.com/3855487/68254229-543afd80-002a-11ea-8008-f161c8b592f6.png)

Das Datum und die Monate sollten im Format ausgegeben werden, das beim Benutzer ausgewählt ist, also bspw. de_de - eine enstprechende Formatierung liefert REDAXO im Core gleich mit:

https://github.com/redaxo/redaxo/blob/c9315d45806977b06896e4b63b0024bf70b11d9d/redaxo/src/core/lang/de_de.lang#L6

**Comment by skerbis** [comment]
Das Format entspricht der ISO 8601

**Comment by alexplusde** [comment]
Ja. Aber die Darstellung dort ist für Menschen in einer GUI - nicht für Maschinen.

**Comment by skerbis** [comment]
bleibt so
