### ISSUE TITLE
Neuen Ort inline bei einem neuen Termin anlegen können (auch: Kategorie)

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/sked#145]
Ähnlich wie die Inline Relations von YForm sollte man während der Termineingabe einen Ort anlegen können, wenn es ihn noch nicht gibt.

Wäre auch für Kategorien super.

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/sked/issues/135

**Comment by alexplusde** [comment]
(wegen mir braucht es das nicht mehr)
