### ISSUE TITLE
Verkehrte Datumsformatierung bei 0000-00-00 (ohne Enddatum)

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/sked#146]
![image](https://user-images.githubusercontent.com/3855487/68254586-230efd00-002b-11ea-8419-e8b216d28e63.png)

hier würde ich nicht den das Jahr vor Christi Geburt erwarten in der Ausgabe.

**Comment by skerbis** [comment]
wo findet sich diese Darstellung? Wie wurden die Daten abgerufen?

**Comment by alexplusde** [comment]
Die Darstellung findest du in der Übersicht von Sked bei den Terminen als Liste.

**Comment by skerbis** [comment]
da ist was wuschig bei Dir

**Comment by alexplusde** [comment]
Hapffffff! Ich schau es mir nochmal an oder schick dir einen Zugang

**Comment by skerbis** [comment]
und @alexplusde ?

**Comment by skerbis** [comment]
ping @alexplusde

**Comment by joachimdoerr** [comment]
Kein Feedback. close.
