### ISSUE TITLE
Eintrag ohne Ort / Kategorie ermöglichen

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/sked#147]
Wurden einmal Orte / Kategorien in der Liste hinterlegt, werden diese beim Erstellen oder Bearbeiten eines Eintrags vorausgewählt. Eine "Bitte wählen"- / Leeroption wäre gut.

Workaround: mit id=1 einen leeren Eintrag anlegen.

**Comment by skerbis** [comment]
Ein Kalendereintrag ohne Kategorie ist nicht möglich. Die Kategorie ist der Kalender , vgl. iCal

**Comment by alexplusde** [comment]
Dann sollte zur Installation eine Kategorie (und ein Ort) initial erstellt werden.

**Comment by joachimdoerr** [comment]
Wir sollten die Kategorie umbenennen in Kalender und hier keine Vorinstallation sonder ein Info Warning Hinweis ausprinten und es verhindern, dass man ein Eintrag anlegen kann vordem es ein Kalender gibt.
