### ISSUE TITLE
Screenshots / Doku anlegen

### ISSUE THREAD

**Issue by Hirbod** [FriendsOfREDAXO/sked#15]
:)

**Comment by schuer** [comment]
Für Screenshots wäre vielleicht noch #25 interessant.

**Comment by aeberhard** [comment]
@skerbis Hallo Thomas,
 schau doch mal im Demo-Addon nach https://github.com/FriendsOfREDAXO/demo_addon

Hier gibt es ein **plugin documentation**, das kann man als Basis für die eigene Dokumentation eines Addons verwenden. Ich baue das auch gerade beim demo_fullpage ein statt der INFO.md.

Die Dokumentation des plugins ist eine Beschreibung für das Vorgehen um das anzupassen :)

**Comment by skerbis** [comment]
@aeberhard danke, damit wird‘s auch gemacht. 👍

**Comment by aeberhard** [comment]
@skerbis kleines Update des Plugins ... Anzeige des dokument-Namens!

**Comment by alexplusde** [comment]
Wir werden das Addon einsetzen, ich würde wieder anbieten, einen Teil der Doku zu schreiben, wenn das Doku-Plugin hier Einzug findet. Ich kann mich nur leider nicht mit der Plugin-Vorlage beschäftigen, sondern nur Text und Kapitel liefern.

**Comment by skerbis** [comment]
@alexplusde wird gemacht

**Comment by alexplusde** [comment]
## Sammelbecken: Kalenderdaten per Datenbank abfragen und lokalisiert ausgeben.

```
setlocale(LC_TIME, "de_DE.utf8", "de_DE", "de");
$entry_ids = rex_sql::factory()->setDebug(0)->getArray('SELECT id FROM rex_sked_entries WHERE status > 0 LIMIT 5');
foreach ($entry_ids as $entry_id) {
$entry = array_shift(\Sked\Handler\SkedHandler::getEntry($entry_id['id']));
    //dump($entry);
$startdate = strftime("%a., %e. %B %Y", $entry->entry_start_date->getTimestamp());
$enddate = strftime("%a., %e. %B %Y", $entry->entry_end_date->getTimestamp());
$starttime = substr($entry->entry_start_time,0,5);
$endtime = substr($entry->entry_end_time,0,5);
?>
	<div class="entry">
		<div class="calendar-page">
			<span class="month"><?php echo strftime("%b", $entry->entry_end_date->getTimestamp()); ?></span>
			<span class="day"><?php echo strftime("%d", $entry->entry_end_date->getTimestamp()).'.'; ?></span>
		</div>
```

> Hinweis: Link zur Doku für die PHP-DateTime-Klasse: http://php.net/manual/de/class.datetime.php
> Hinweis: Das PHP-DateTime-Objekt kann nicht lokalisierten Text ausgeben, daher strftime(). Liste der Parameter http://php.net/manual/de/function.strftime.php
> Hinweis: `$entry->entry_start_date->getTimestamp()` gibt den Start-Zeitpunkt ohne Beginn-Uhrzeit aus. Diese muss ggf. hinzu addiert werden. (Todo)

**Comment by skerbis** [comment]
Screenshot check, Doku hier: 
https://github.com/FriendsOfREDAXO/sked/tree/master/plugins/documentation 
Erste Artikel sind angelegt

**Comment by alexplusde** [comment]
Verweise auf das demo_addon gehören noch weg und die richtigen Namen in die Credits

**Comment by skerbis** [comment]
@alexplusde Deine Spielwiese ;-)

**Comment by skerbis** [comment]
Die readme ersetzt das doku Plugin
