### ISSUE TITLE
Beispiel für die Kombination von Sked und dem URL-Addon

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/sked#150]
Ich würde eins schreiben - aber ich benötige einen Tipp, wie man bspw. eine Validierung in Sked einfügt. Konkret würde ich mir wünschen, dass der Titel einer Veranstaltung oder eine Kombination daraus unique ist. 

Weiß jemand, was passiert, wenn man das direkt an der Datenbank einstellt?

**Comment by skerbis** [comment]
Kombiniere id und Titel? das wäre doch unique

**Comment by alexplusde** [comment]
Du meinst direkt an der Datenbank?
