### ISSUE TITLE
Darstellungsfehler in der Doku

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/sked#151]
![image](https://user-images.githubusercontent.com/3855487/68257633-38d4f000-0034-11ea-8b4a-321ef9dde5a5.png)

**Comment by skerbis** [comment]
Ich würde das PlugIn ganz entfernen und stattdessen es mit einer README.md  bauen.

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/sked/commit/9350971e83c539f22a14916f33a760e9c4f05b84
