### ISSUE TITLE
Redactor Editor wird erst sichtbar, wenn das Profil gespeichert wurde

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/sked#152]
Sieht so aus, als ob der Redactor-Cache nach dem Installieren von Sked gelöscht werden muss.

**Comment by skerbis** [comment]
gibt es eine Methode / Funktion dafür?

**Comment by skerbis** [comment]
Da sich beim Redactor aktuell nichts tut . vorerst close
