### ISSUE TITLE
Add-Buttons in Monatsansicht verschwinden

### ISSUE THREAD

**Issue by bitshiftersgmbh** [FriendsOfREDAXO/sked#156]
**Ausgangslage:** Wenn man in der Monatsansicht ist, hat man die runden "+" Buttons zum Adden von Terminen. Klappt!

**Bug:** Wenn man nun auf die Wochenansicht wechselt und wieder zurück auf Monatsansicht sind die Buttons verschwunden. Wenn man dann links/rechts blättert, kommen sie wieder.

**Nebenfrage:** Ist es richtig so, das man in der Wochenansicht nur gucken kann aber nicht direkt Termine anlegen? Dann wäre die Ansicht eigentlich bisschen _sinnlos_ ;)

**Comment by joachimdoerr** [comment]
9db7563c65c3904ec031092a8e267a8d0fd06069
