### ISSUE TITLE
Mehrere Kategorien für einen Termin

### ISSUE THREAD

**Issue by voteros** [FriendsOfREDAXO/sked#160]
Hallo,
aktuell habe ich das gleiche Problem wie Issue #57 . Wurde der Gedanke, einem Termine mehrere Kategorien zuweisen zu können, vollständig verworfen, oder ist in naher Zukunft damit zu rechnen? Die Erklärung, die Kategorien sind eher als unterschiedliche Kalender anzusehen, habe ich gelesen.

Viele Grüße
voteros

**Comment by skerbis** [comment]
Kategorien sind Kalender. Du kannst dir per sqlselect eine eigene Auswahl schaffen
