### ISSUE TITLE
Sked 1.10.0: Beim Update wird das Doku-Plugin nicht gelöscht.

### ISSUE THREAD

**Issue by DanielWeitenauer** [FriendsOfREDAXO/sked#161]
Ein aus vorhergehenden Installationen vorhandenes Doku-Plugin wird beim Update auf v1.10.0 nicht gelöscht.

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/sked/commit/be0cd332e123eef5cf16ef875954938ca3580a10
