### ISSUE TITLE
yForm-Datensätze anhängen

### ISSUE THREAD

**Issue by danspringer** [FriendsOfREDAXO/sked#164]
Eben im Slack drüber gesprochen:
Es wäre evtl hilfreich, wenn man einem Termin mit einem custom-Field einen/mehrere Datensätze aus einer yForm-Tabelle zuordnen könnte. 
Ggf. könnte man die Daten aus den Datensätzen noch in irgendeiner Form beim Datensatz anzeigen.

Konkretes Anwedungsbeispiel:
Ein Sked-Termin kann vom User über das FE gebucht werden. Der Buchungsvorgang legt in einer yForm-Tabelle einen Datensatz mit den Buchungsdetails an.
Der Sked-Termin soll nun mit den Buchungsdaten des yForm-Eintrags "verbunden" werden.

Gedankenstütze von @skerbis:

> Hmm vielleicht ein ep an der richtigen Stelle , damit man die Ausgabe manipulieren kann.

**Comment by skerbis** [comment]
ähnlich: https://github.com/FriendsOfREDAXO/sked/issues/78

**Comment by skerbis** [comment]
Alternativ einfach n SQL-Select?
