### ISSUE TITLE
v1.8.0: Termine werden in Liste und Monatsansicht korrekt angezeigt, in Wochenansicht jedoch an falschem Tag

### ISSUE THREAD

**Issue by bitshiftersgmbh** [FriendsOfREDAXO/sked#168]
Gab es da schon mal Bugs, die evtl. in 2.0.x behoben wurden? Dann direkt Ticket verwerfen bitte. In Kürze wird bei dem Kunden Sked auch geupdated.

![Screenshot 2020-10-20 141201](https://user-images.githubusercontent.com/7023022/96585072-5cde1f80-12df-11eb-8132-4a1c5871e9a7.png)

**Comment by skerbis** [comment]
Kann ich bei mir (aktuelle Version) nicht reproduzieren. Ein Update sollte problemlos möglich sein.
