### ISSUE TITLE
Multikategoriefähigkeit einbauen

### ISSUE THREAD

**Issue by joachimdoerr** [FriendsOfREDAXO/sked#18]

**Comment by joachimdoerr** [comment]
d74dd59f27b76bb7427b84a247ff0747061cb6b8

**Comment by skerbis** [comment]
Ich sehe kein Feld zur multiplen Auswahl

**Comment by joachimdoerr** [comment]
Die bezog sich auf die Ausgabe also die API.

**Comment by skerbis** [comment]
Hier geht's weiter: https://github.com/FriendsOfREDAXO/sked/issues/57
