### ISSUE TITLE
Reihenfolge der Tabs einstellbar machen

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/sked#2]
Kalender / Termine
Termine / Kalender

**Comment by joachimdoerr** [comment]
Macht das wirklich sinn? Ich finde das landen auf dem Kalender-Blatt Sinnvoll.

**Comment by skerbis** [comment]
Ich denke, es würde auch reichen, wenn man festlegt welcher Tab geöffnet sein soll oder das Addon merkt sich welcher Tab zuletzt geöffnet war.

**Comment by svenkaemper** [comment]
Die Kalenderansicht ist ganz nett, aber eine nach Datum aufsteigend (!) sortierte Liste mit Kalendereinträgen fände ich als default-Einstellung auch hilfreicher. 

Zudem ist mir aufgefallen, dass man über die Kalenderansicht zwar die Einzelansicht eines Termins öffnen kann, aber wenn man den Termin dann speichert, landet man in der Listenansicht.

**Comment by skerbis** [comment]
PR WELCOME

**Comment by eaCe** [comment]
Kann ich auch noch übernehmen - Ich würde in den Einstellungen anbieten entweder den Kalender-View oder die Termin-Übersicht als Startseite anzeigen zu lassen.

**Comment by skerbis** [comment]
👍

**Comment by skerbis** [comment]
Danke @eaCe
