### ISSUE TITLE
REX-YouCanBookMe :: Google-API integrierbar? > neues AddOn aufbauend auf diesem?

### ISSUE THREAD

**Issue by madiko** [FriendsOfREDAXO/sked#21]
Um den Webnutzern ein Buchungssystem zum Termine vereinbaren anbieten zu können, wäre noch eine Integration (Lesen und Schreiben) mit Google-Kalender klasse. Dabei brauche ich die Möglichkeit, unterschiedliche Google-Kalender innerhalb einer REX-Instanz einfügen zu können.

Bisher löste ich das mit YouCanBookMe (https://youcanbook.me). 

Eine YouCanBookMe-REX-Lösung wäre genial. Wenn es interessant ist, arbeite ich gern am Konzept mit. Oder braucht es ein eigenes AddOn dafür, das vielleicht auf diesem hier aufbaut? Was meint Ihr?

**Comment by skerbis** [comment]
Warum ausgerechnet Google? Dieser Kalender könnte das doch selbst erledigen.

**Comment by madiko** [comment]
Hallo Thomas @skerbis,

vielen Dank für die superschnelle Antwort und Pardon - das wichtigste habe ich vergessen: 

Ich kann YouCanBookMe sagen, wann ich grundsätzlich gebucht werden möchte (und wann nicht). Darüber hinaus holt sich das Tool meine aktuelle Verfügbarkeit (über den Google-Kalender) - sprich, wo ich schon ausgebucht bin.

In Anwendung sieht das so aus: http://madiko.com/termin-buchen
(Achtung: Es gibt momentan einen Bug beim Aufruf via Smartphone. Die reine YouCanBookMe-Funktionalität ist zu sehen - der Rest der Seite jedoch nicht. Da ich ohnehin am Relaunch arbeite, hab ich da grad nicht die Priorität).

Viele Grüße,
Franziska

**Comment by skerbis** [comment]
Grundsätzlich finde ich die Idee einer Booking-Möglichkeit gut. Ob ich es unbedingt abhängig von einem Dienst machen will ist eine andere Frage. (Könnte über ein syncing realisiert werden). 
Solche Funktionen können aus meiner Sicht im Rahmen von Kundenprojekten finanziert werden.  Es ist nicht trivial es umzusetzen. Kommt Projekt, kommt Lösung ;-) - Stimmt's @joachimdoerr ?

**Comment by joachimdoerr** [comment]
Stimmt das ist ganz und gar nicht trivial. Aber ein Booking würde durchaus Sinn machen. Wobei ich das eher als Plugin für Sked sehe. Ich würde eher weniger auf Externe Dienste verzichten vor allem bei Google kann sich schnell vieles ändern bis dahin, dass der Dienst eingestellt wird.

**Comment by madiko** [comment]
Zum Thema "Kommt Projekt - kommt Rat": Für mein Portal ist das geplant. Das ist eine Funktion, die von allen gewünscht wird. Ich könnte mir vorstellen, dass wir also eine Schwarmfinanzierung / Finanzierung über das Portal hinbekommen würden.

Es wäre klasse, wenn eine Eigenprogrammierung möglich wäre. Wenn nicht, würde ich wieder auf YouCanBookMe / Google zurückgreifen. Doch aus den genannten Gründen wäre mir Option 1 lieber.

Für das Crowdfunding: Wie schätzt Ihr den Aufwand ein? Sollen wir dazu mal skypen, um das gemeinsam abzuwägen? 

Es gibt zwei Möglichkeiten, das zu finanzieren:

(1) Konventionell
Unternehmerisches Risiko aber auch die Erfolge liegen bei mir. Wir brauchen allerdings aufgrund meiner aktuellen wirtschaftlichen Lage einen Finanzierungsplan - was auch vom Aufwand abhinge (siehe oben).

(2) WertVertrag
Wir investieren als Partner in die Idee und teilen uns Erfolge und Risiko bzw. Aufwand (das kann auch an die Community gehen, zum Beispiel zur Finanzierung der REDAXO-Tage oder ähnlich). 

Die Anteile errechnen sich aus der Kooperationsmatrix des WertVertrags. WertVerträge sind auf Dauer angelegt und entkoppeln Zeit gegen Geld. Stattdessen sind sie marktorientiert und agil. Nachdem zunächst geklärt wird, wie die Wertanteile der einzelnen Aufgabenblöcke verteilt werden und die Partner sich darüber einig geworden sind, wer welchen Anteil übernimmt (= Kooperationsmatrix) lässt sich der Wertanteil des Einzelnen für's Vorhaben errechnen. Daraus kann dann der Preis / das Honorar abgeleitet werden.

Gern kann ich - nach einem ersten Sondierungsgespräch - einen Vorschlag für den WertVertrag machen. Diesen entwickeln wir dann gemeinsam weiter. Was sich jetzt recht abstrakt anhört, wird am konkreten Fallbeispiel dann einfach zu verstehen und anzuwenden.

Die detaillierte Anleitung folgt noch (das ist eines der Projekte, an denen ich arbeite). Wer schon mehr wissen will, hier steht wie ich sie nutze:
http://madiko.com/leistungen/wertvertraege-mit-madiko/
... und eine erste öffentliche Anleitung von Gebhard Borck und mir (mit dem ich das Geschäftsmodell entwickelte)
http://WertVerträge.de

Wer daran interesse hat, mitzuwirken: Bitte bei mir melden.

**Comment by madiko** [comment]
Noch ein Gedanke dazu: Vielleicht ist das auch sked-booking bzw. noch besser REXbooking (also ein neues AddOn - das nur eben auf sked aufbaut?).

**Comment by joachimdoerr** [comment]
Ich bin da offen. Hört sich ja spannend an :) Die frage ist wie gefragt ist das Booking Feature? Eine Finanzierung über die Community seh eher nicht, das ist extrem mühselig und entspricht aus meiner Sicht auch nicht der führenden Mentalität der Redaxo Community Member.

**Comment by skerbis** [comment]
ich close das mal
