### ISSUE TITLE
Beispielmodul :: Kalenderblatt

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/sked#23]
Wow, eben ausprobiert, bin begeistert vom Stand der Dinge. Was natürlich schön wäre: Den Kalender vom Backend als Ausgabe fürs Frontend ermöglichen.

**Comment by skerbis** [comment]
nur zu 👍

**Comment by alexplusde** [comment]
@cukabeka du meinst die Darstellung als Kalenderblatt?

**Comment by fw-thomas74** [comment]
Kalenderblatt würde es übersichtlicher aussehen wenn mal alle Termine auf ein Blick haben möchte

**Comment by alexplusde** [comment]
Ich finde Listen übersichtlicher, aber das ist Geschmackssache. Darfst gerne die Doku ergänzen, das JS liegt ja dem Addon bei.

**Comment by fw-thomas74** [comment]
Im welchen Ordner liegt es?

**Comment by skerbis** [comment]
Eine Anleitung dazu gibt es bereits
