### ISSUE TITLE
Sync mit anderen Kalenderdiensten (Google)

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/sked#26]
Vielleicht auch nur ein initialer Import der Google Daten?

Ist vielleicht ne Idee... (vielleicht auch nicht. Dann einfach schliessen)

**Comment by joachimdoerr** [comment]
Sicher ist das eine sogar sehr wichtige Sache. Ich denke das würde am besten als Plugin für Sked gelöst werden.

**Comment by alexplusde** [comment]
Ich bin dran. Freue mich über Beteiligung und das Addon wird gerne, wenn es stabil ist, zu FOR übertragen.
https://github.com/alexplusde/sked_ics
