### ISSUE TITLE
Ausgabe im Kalender auch wenn keine Kategorie gesetzt ist

### ISSUE THREAD

**Issue by eaCe** [FriendsOfREDAXO/sked#27]
Ich denke es wäre gut wenn die Ausgabe im Kalender nicht auf eine gesetzte Kategorie und location besteht. Wenn man diese Angaben nicht benötigt kann man zwar ein Dummy anlegen, aber ich halte diese Angaben für optional.

**Comment by joachimdoerr** [comment]
Ja das seh ich auch so.

**Comment by joachimdoerr** [comment]
Done. 9f5871963fe069cfe3e993e0714c4687e914fdfb
