### ISSUE TITLE
Fehler beim Speichern der Kategorie

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/sked#28]
Ich hatte gerade das Problem, keine Kategorie anlegen zu können. Es kam immer »Fehler beim Speichern«. Am Ende lag es offenbar an Sprachen oder Metadaten, die von der Basisdemo angelegt worden waren. Ich habe es nicht weiter nachverfolgt, aber als ich Englisch gelöscht hatte, so dass nur noch Deutsch übrig war, kam der Fehler nicht weiter vor.

Fehlersituation also: Frisches REDAXO, Basisdemo installieren, Sked installieren. -> Fehler.

**Comment by skerbis** [comment]
Gerade in Nicht-Demo (also Standard-Installation) getestet. Alles soweit ok. Steht was in den Logs?

**Comment by dtpop** [comment]
Unknown column 'description' in 'field list'
mit Debug ermittelt
