### ISSUE TITLE
Setttings - Fehler

### ISSUE THREAD

**Issue by Goldfischpeter** [FriendsOfREDAXO/sked#31]
Zeile 30
ist
\Sked\Utils\Sked**f**EditorHelper::addEditorSets();

sollte?
\Sked\Utils\SkedEditorHelper::addEditorSets();

Zeile 91
ist
$elements['field'] = '
  <input type="submit" class="btn btn-save rex-form-aligned" name="config[submit]" value="' . rex_i18n::msg('mblock_config_save') . '" ' . rex::getAccesskey(rex_i18n::msg('mblock_config_save'), 'save') . ' />
';

sollte
$elements['field'] = '
<input type="submit" class="btn btn-save rex-form-aligned" name="config[submit]" value="' . rex_i18n::msg('sked_config_save') . '" ' . rex::getAccesskey(rex_i18n::msg('sked_config_save'), 'save') . ' />
';

**Comment by joachimdoerr** [comment]
Thanks @Mike Lang und @Goldfischpeter für die Hinweise. Ist soweit gefixt: https://github.com/FriendsOfREDAXO/sked/commit/f3f37bb67858116b8796bcc9c13d202576e1208d
