### ISSUE TITLE
Zusätzliche Felder (Sammel-Issue)

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/sked#32]
benötigt für APIs, structured data, o.ä.
bspw.: 

* Preis(e)
* Einlass
* Ticket-URL

Noch besser: Eigene Felder anlegen können.

**Comment by skerbis** [comment]
Du kannst eigene Felder anlegen. Mehr Infos dazu im nächsten Release

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/sked/pull/30/commits/9d4f7dfb3452e07fa2e39187af10e72a8f338f09

**Comment by alexplusde** [comment]
Falls es dir einfacher fällt, nur einen Rohentwurf zu schreiben, dann, kann ich ihn gerne ausformulieren.

Für Veranstaltungen finde ich allerdings, könnte auf jeden Fall ein Preis, Einlass-Uhrzeits und URL-Feld verpflichtend drin sein.

Vlt. kann man die YML auch so konfigurieren, dass man umgekehrt unbenötigte Felder ausblenden kann?

**Comment by skerbis** [comment]
Ich würde es bei den Grundfeldern belassen und es entsprechend gut dokumentieren. Manche Leute benötigen nur Titel und Info andere ein komplettes Buchungssytem ...

**Comment by alexplusde** [comment]
Wie sieht es aus mit lat/lng für Orte, die geocodiert werden können? (siehe yform geo-plugin)

**Comment by skerbis** [comment]
Das ist ne tolle Idee, gerne dafür ein neues Issue aufmachen

**Comment by alexplusde** [comment]
Hab ich gemacht. Dann hätte ich hier noch die fehlende Option "ganztägig", um unterscheiden zu können, ob ein Termin mit oder ohne Uhrzeit ist. Denn `00:00` und `ohne Uhrzeit` sind zwei paar Schuhe.

**Comment by skerbis** [comment]
ist auch eher ein eigener Issue. Samuel-Issues sollten wir nicht machen @alexplusde, das geht unter.

**Comment by alexplusde** [comment]
Einverstanden, ich wollte es nur zunächst transparent diskutieren, bevor daraus ein Issue wird.

**Comment by svenkaemper** [comment]
Wenn ich das in der Doku richtig sehe, stehen aktuell folgende Feldtypen für eigene Felder zur Verfügung: 

- media,
- medialist, 
- text,
- textarea, 
- Link, 
- Linklist

Ich fände es sehr hilfreich, wenn man zusätzlich noch Checkboxen und/oder Radiobuttons anlegen könnte (Beispiel öffentlicher/nichtöffentlicher Termin).

**Comment by skerbis** [comment]
PR Welcome

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/sked/pull/52/commits/ad907c942c06bcd86090aaa2eed7a57e97e42a67
