### ISSUE TITLE
Sked Kalender // CSRF-Token ungültig…?

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/sked#33]
https://redaxo.org/forum/addons-packages-r5-f43/sked-kalender-csrf-token-ungueltig-t22048.html

**Comment by eaCe** [comment]
Das Problem ist (ich denke) kein sked spezifisches. Ich habe am Wochenende den gleichen Fehler bekommen, wenn ich in den Metadaten den Status von offline auf online stellen wollte.

**Comment by alexplusde** [comment]
Ist das inzwischen gefixt?

**Comment by skerbis** [comment]
Kann ich aktuell unter REDAXO 5.5.1 nicht reproduzieren.

**Comment by skerbis** [comment]
vorerst close
