### ISSUE TITLE
Reiter mit Icons ausstatten

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/sked#34]
Wie bei search_it

![image](https://user-images.githubusercontent.com/3855487/34904402-6a3a7938-f845-11e7-9b60-335769908cca.png)

**Comment by skerbis** [comment]
Vorschläge?

**Comment by alexplusde** [comment]
fa-calendar für Übersicht
fa-calendar-plus-o für Einträge / Termine
fa-folder / fa-folder-open für Kategorien
fa-map-marker für Orte/Locations
fa-cogs für Einstellungen

**Comment by skerbis** [comment]
![bildschirmfoto 2018-01-13 um 10 30 59](https://user-images.githubusercontent.com/791247/34904762-de6c5be4-f84c-11e7-98ba-d9bda6b5e070.png)

https://github.com/FriendsOfREDAXO/sked/commit/bd974573c03bf94e3a78a3f7c3f00221469bda42
