### ISSUE TITLE
Farbwähler defekt

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/sked#36]
Beim Klick auf den Farbwähler kommt bei mir:
```
ReferenceError: trigger is not defined
 /assets/addons/sked/sked.js?buster=1515681031:344
```

**Comment by skerbis** [comment]
Bei mir alles ok
![bildschirmfoto 2018-01-13 um 09 44 38](https://user-images.githubusercontent.com/791247/34904444-6f08fe02-f846-11e7-8e97-410c59cb53c4.png)

**Comment by alexplusde** [comment]
Nach dem Update wurde evtl. der Cache nicht gelöscht. Nach dem Cache löschen funktioniert es. Muss hier das Cache löschen getriggert werden?

**Comment by skerbis** [comment]
ist hier auch ein Update …

**Comment by alexplusde** [comment]
ich werd das mal beobachten, war aber wirklich so. Einfacher Browser-Reload hat nicht gereicht.

**Comment by skerbis** [comment]
Vorerst close
