### ISSUE TITLE
Location-Labels nicht in lang-Datei

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/sked#37]
Da stehen die wohl noch hart codierten Texte als Labels drin.

**Comment by skerbis** [comment]
Bitte Code-Stellen nennen

**Comment by alexplusde** [comment]
Ah, das kommt daher, dass die nicht Teil des Addons sind, sondern in der Feld-Definition:
https://github.com/FriendsOfREDAXO/sked/blob/master/data/definitions/venues.yml
