### ISSUE TITLE
Orte geocodieren

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/sked#38]
analog zum geo-plugin von yform.

**Comment by skerbis** [comment]
Evtl. auf Basis vonhttps://github.com/FriendsOfREDAXO/yform_geo_osm um unabhängig von Google zu bleiben.

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/yform_geo_osm/issues/2

**Comment by skerbis** [comment]
sollte ei n anderes AddOn liefern
