### ISSUE TITLE
API-Calls

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/sked#40]
// API-Call
http://redaxo5/index.php?rex-api-call=sked_exchange&start=2017-08-17&end=2017-12-08&category=1&venue=1
Einzel-Event
das wäre z.b. : http://redaxo5/index.php?rex-api-call=sked_exchange&id=4
und date range
http://redaxo5/index.php?rex-api-call=sked_exchange&start=2017-08-17&end=2017-12-08&short=0

von @skerbis

**Comment by skerbis** [comment]
@joachimdoerr magst ein bisschen mehr dazu schreiben, so dass Alex es dokumentieren kann?

**Comment by alexplusde** [comment]
wegen mir braucht's das nicht mehr.
