### ISSUE TITLE
Feld "ganztägiger Termin"

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/sked#42]
Die Option "ganztägig" fehlt, um unterscheiden zu können, ob ein Termin mit oder ohne Uhrzeit ist. Denn 00:00 und ohne Uhrzeit sind zwei paar Schuhe.

**Comment by alexplusde** [comment]
Im Moment erweitere ich in `sked_ical` die Sked-Tabelle um das Feld `is_fulltime`. Noch ist es in der Entwicklung und es ließen sich leicht Sachen ändern. Was wäre dein Vorschlag @skerbis?

https://github.com/alexplusde/sked_ics/blob/0.1/boot.php#L10

**Comment by skerbis** [comment]
Mein Vorschlag wäre es eher in Sked direkt zu realisieren, damit Deine Lösung es nutzen kann. Es macht nicht viel Sinn, wenn eine "wichtige" Funktion erst mit einem PlugIn/ AddOn  kommt.

**Comment by alexplusde** [comment]
Deswegen zumindest die Frage, wie das Feld in der Datenbank heißen müsste.

Für die Eingabe muss dann sichergestellt sein, dass die Uhrzeit leer ist. Also mindestens 00:00, streng genommen eigentlich NULL. Der End-Tag muss mind. 1 größer sein als der Start-Tag.

**Comment by skerbis** [comment]
In der DB würde ich es fulltime nennen analog zu repeat

**Comment by skerbis** [comment]
Demnach gibt es schon eine Möglichkeit für ganztägige Termine. 
https://github.com/FriendsOfREDAXO/sked/issues/42

**Comment by alexplusde** [comment]
Ich bin mir nicht sicher, ob durch Verarbeitungsprozesse die Information eines ganztägigen Datums verloren geht und sehe da ein separates Feld als nützlich an.

**Comment by joachimdoerr** [comment]
485fac5212770b72e8c1afd8f5838a2520567dea

**Comment by alexplusde** [comment]
Was genau wurde gemacht?

**Comment by skerbis** [comment]
@alexplusde am besten mal das aktuelle REPO zum testen installieren

**Comment by skerbis** [comment]
@alexplusde https://github.com/FriendsOfREDAXO/sked/blob/master/CHANGELOG.md
