### ISSUE TITLE
Ortsfelder: lat/lng statt lon/lat (Reihenfolge, Name)

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/sked#43]
Reihenfolge und Bezeichnung ist verkehrt:
https://github.com/FriendsOfREDAXO/sked/blob/master/data/definitions/venues.yml#L22

Kann man das gefahrlos ändern? Oder müssten bei einem Update nicht auch die bestehenden Daten aktualisiert werden?

**Comment by skerbis** [comment]
du kannst die labels ändern

**Comment by alexplusde** [comment]
aber nicht die Feldnamen, oder? Standard wäre, sie lat/lng zu nennen. Finde das irritierend, wenn die bei der Abfrage plötzlich anders heißen.

**Comment by skerbis** [comment]
Aktuell werden sie nirgends verwendet. Könnten also umbenannt werden. Werden diese jedoch schon von irgendeinem User verwendet, werden diese bei einem Update verschwinden.
