### ISSUE TITLE
WYSIWYG Editor einstellen

### ISSUE THREAD

**Issue by eaCe** [FriendsOfREDAXO/sked#44]
Oder via EP/Methode die Möglichkeit schaffen einen anderen außer Redactor zu nutzen. Das wäre schön :)

**Comment by skerbis** [comment]
PR welcome

**Comment by eaCe** [comment]
Dazu sollte man vielleicht erst klären wie man das ganze am besten anfängt.
Ich persönlich denke ja es reicht wenn man eigene Attribute/Klassen auf die beiden Textareas schreiben kann, ähnlich wie bei YForm.

**Comment by skerbis** [comment]
@eaCe sehe ich auch so

**Comment by skerbis** [comment]
PR Welcome ;-)

**Comment by eaCe** [comment]
Habe das bei mir mal gepushed:
https://github.com/eaCe/sked

Sollte funktionieren. Ich denke ich muss die Attribute dann aber auch in SkedFormFieldsetHandler setzen?

**Comment by skerbis** [comment]
Sollte nicht nötig sein, da man jedem custom field eigene Attribute geben kann.

**Comment by eaCe** [comment]
Oh, habe eben einen neuen Stand gepushed :) dann setze ich das wieder zurük

**Comment by skerbis** [comment]
Wird released in 1.5.0 - Danke
