### ISSUE TITLE
Ein Termin - mehrere Kategorien

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/sked#57]
Der ICS-Standard lässt es zu, einem Termin mehrere Kategorien zuzuordnen. Hierzu 
* können wir das bestehende Feld `category` nutzen und erweitern
* können wir ein neues Feld `categories` einfügen, indem die ids der Kategorien kommagetrennt eingetragen werden. 

Außerdem müssten wir dann das Eingabefeld in den Sked-Terminen ändern.

Bei einem Update von Sked müssten dann die bestehenden IDs aus `category` nach `categories` übertragen werden - soll aus Kompatibilitätsgründen das Feld category erhalten bleiben oder gelöscht werden?

@skerbis kannst/möchtest du das umsetzen?

**Comment by skerbis** [comment]
Keine Zeit im Moment. Leider.

**Comment by alexplusde** [comment]
Ich bräuchte zumindest eine Entscheidung

**Comment by skerbis** [comment]
@joachimdoerr darf entscheiden. Ich bin nur das kleine Helferlein

**Comment by skerbis** [comment]
Es stellt sich auch die Frage, wie sollen Termine mit mehreren Kategorien im Backend-Kalender dargestellt werden? Ist nicht so einfach.

**Comment by alexplusde** [comment]
Analog zu anderen Kalendersystemen mit unterschiedlichen Kalendern: Den Termin mehrfach anzeigen und Kategorien filtern können. 

Oder die erste Kategorie als primäre Kategorie verwenden. Oder Termine neutral darstellen ohne Farbe, solange keine Kategorie gefiltert wurde.

Es sollte auf jeden Fall nicht daran scheitern.

**Comment by joachimdoerr** [comment]
Wenn man das mit deiner Logik verfolgt also category als feld belässt kann man dieses als Master-Kategorie führen. Im Backend-Kalender würden dann nur die Events aus der Master-Kategorie angezeigt. Wenn man mehrere Kategorien haben möchte könnte man dann auf das Zweite Feld zurück greifen, ich gehe mal davon aus, dass dies eher selten der Fall sein wird.

**Comment by skerbis** [comment]
Die Kategorien, sind allerdings nicht als unterschiedliche Kalender zu verstehen in sked. Sked ist 1 Kalender mit verschiedenen Veranstatlungs-/Terminkategorien.

**Comment by joachimdoerr** [comment]
Somit hat ein Eintrag jeweils nur die Information, dass er zu einer oder mehreren Kategorien gehört. Mehrere Kategorien eines Eintrages bedingen nicht, das dieser Eintrag gedoppelt wird, sofern man filter auf mehrere Kategorien laufen lässt.

**Comment by alexplusde** [comment]
Dann lege ich `sked_ics` so an, dass ein Feld `cateogries` angelegt wird, in dem dann IDs von mehreren Kategorien abgelegt werden - für die Eingabe / Verwaltung muss man sich dann ggf. was überlegen.

**Comment by skerbis** [comment]
Ja ein Feld zusätzliche Kategorien, vielleicht?

**Comment by alexplusde** [comment]
Alternative Idee: Einen Reiter Tags definieren, ICS-Kategorien lieber als Tags anlegen und Kategorie samt Darstellung so lassen, wie sie ist.

**Comment by steri-rex** [comment]
Wollte mich erkundigen wie der Stand diesbezüglich ist. In der feature Liste von Sked steht u.a.: _Mehrfachkategorisierung der Einträge_
wenn ich das richtig verstehe gibt es dieses feature noch nicht - zumindest lässt sich aktuell nur eine kategorie beim termin auswählen.
Oder gibt es da schon eine Möglichkeit?

**Comment by skerbis** [comment]
@steri-rex ist aktuell nicht möglich. Aktuell kann man nur Einträge mehrer Kategorien listen.

**Comment by joachimdoerr** [comment]
@alexplusde das mit den Tags find ich sehr gut! Aber sicher auch verwirrend für Redakteure oder?

**Comment by alexplusde** [comment]
An welcher Stelle verwirrend? Du meinst, wann Kategorien und wann Tags angelegt werden sollen?

**Comment by joachimdoerr** [comment]
Es gäbe ja dann 2 Eingaben einmal für die "Master" Kategorie und optional für Sonstige Kategorien oder Tags.

**Comment by skerbis** [comment]
Hmmm...Hier stimmt irgendwas nicht. Eigentlich sind die Kategorien, die wir jetzt haben eher die Kalender in iCal - richtig? Auch da kann ich nicht einen Termin mehreren Kalendern zuordnen. Also, ich würde die Namen danders festlegen: Aus Kategorien werden Kalender zusätzlich gibt es Kategorien oder man erstellt sich selbst welche über die Custom-Fields, die dann multiple sein können. Was man nun braucht ist, das ganze filtern zu können.

**Comment by skerbis** [comment]
Nach Absprache mit Joachim, haben wir uns entschieden die Kategorisierung zu belassen wie sie ist.  Alle anderen Szenarien können durch Custom_Fields realisiert werden.

**Comment by olien** [comment]
Gibt es hier irgendwo ein Beispiel? Ich habe es eigentlich fast immer, dass ein Termin in unterschiedlichen Kategorien vorkommt...

**Comment by olien** [comment]
Muss ich mir später mal ansehen.. kann ich dann die vorhandenen Kategorien auch ausblenden und nur das Multiselect nutzen?

**Comment by skerbis** [comment]
mach eine default Kategorie und blende die Kategorieauswahl ggf. per CSS aus.

**Comment by skerbis** [comment]
oder ... du lässt die Kategorie als Hauptkategorie und machst dein Multiselect für weitere Kategorien

**Comment by olien** [comment]
OK. Danke... Dann verzichte ich aber auf die farbige Darstellung im Kalender. Richtig? 
Ich glaub wenn ich mehrer Kategorien brauche baue ich dass dann lieber mit dem TableManager (bei jeder Webseite für Schulen ist das so... und dort wird immer ein Kalender gebraucht..)

LG
Oliver

**Comment by skerbis** [comment]
@olien Sked ist vergleichbar mit ical ein Termin kann nicht gleichzeitig in mehreren Kalendern sein. Wie oben erwähnt sind die sed-Kategorien als unterschiedliche Kalender anzusehen.

**Comment by alexplusde** [comment]
Ich sehe das mittlerweile auch so: Das sind unterschiedliche Kalender. Kategorien müsste man separat umsetzen. Damit würde ich auch befürworten, dass Sked das so kommuniziert und Kategorien in Kalender umbenennt.

**Comment by olien** [comment]
ok. Ihr habt ja recht :-)) Danke für die Erklärungen!
