### ISSUE TITLE
Datum mit Uhrzeit liefern

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/sked#58]
Datum und Uhrzeit sollten korrekt geliefert werden, diese werden bisher getrennt als Datetime-Objekt Start-/Enddatum geliefert, und als String für Start-/End-Uhrzeit.

Das zwingt einen in Konstrukte wie dem hier, um gescheit damit arbeiten können:
```
$sked_event['date']->entry_start_date->add(new DateInterval("P0000-00-00T".$sked_event['entry']->entry_start_time.""))
```

`$sked_event['date']` sollte immer das korrekte Datum mit Uhrzeit liefern. Allerdings weiß ich nicht, wo hierfür ein PR notwendig ist.

**Comment by joachimdoerr** [comment]
Die Trennung wurde absichtlich so angelegt. Das ermöglichst auch ganztägige events die Uhrzeit unabhängig sind.

**Comment by alexplusde** [comment]
@joachimdoerr das stimmt leider so nicht, da in der Datenbank grundsätzlich 00:00 Uhr gespeichert wird, weil das Datepicker-Skript keine leere Uhrzeit zulässt.

**Comment by skerbis** [comment]
d.h. ganztägige Termine sind schon möglich, der Picker muss also geändert werden.

**Comment by skerbis** [comment]
Jap! Das script sollte nicht initial bei einem leeren Feld was einsetzen, Oder man leert die Felder per Checkbox (Ganztägig)  und schützt sie vor Eingaben.

**Comment by skerbis** [comment]
**Ich denke das muss raus:** https://github.com/FriendsOfREDAXO/sked/blob/dd9bf6683e61eed8c1faa77edd495065270364ea/assets/sked.js#L310-L315 
Zusätzlich evtl. noch eine Checkbox zum leeren?

**Comment by alexplusde** [comment]
Ja, gerne eine Checkbox zum leeren. 

Ggf. sollte überprüft werden, dass das Enddatum mind. 1 Tag höher ist als das Startdatum, wenn ich das richtig sehe. Ein ganztägiger Termin endet mit dem Folgetag. Das könnte für den Nutzer verwirrend sein. Wie wird ihm klar, dass 26. bis 27. März im Datumsfeld bedeutet, dass der Termin am 26. ganztägig ist?

**Comment by skerbis** [comment]
Habe hierzu auch keine Idee im Moment

**Comment by alexplusde** [comment]
Dann wäre ich dafür, die Eingaben von Datum und Uhrzeit zu trennen und über eine Checkbox “ganztägig“ auszublenden und dem Server mitzugeben, dass in der Uhrzeit NULL gespeichert wird., sowie dem Datum in der Datenbank 1 Tag addiert wird, beim Abruf wenn ganztägig wieder ein Tag abgezogen wird.

Wir müssten hier wirklich zwischen Datumswahl und gespeichertem Datum unterscheiden, um gängige Standards einzuhalten.

**Comment by joachimdoerr** [comment]
* Ganztägig sollte ein Select sein -> Es darf dann keine Uhrzeit und kein End-Datum geben wenn ganztägig, die Eingabe kann sich entsprechend via JS anpassen.
* Start-Date und End-Date soll immer als `yyyy-mm-dd h:i:s` geliefert werden

**Comment by joachimdoerr** [comment]
API Format: 
```[
    {
        "id": "1",
        "title": "Test",
        "date_time": {
            "date": "20.04. - 21.04.",
            "time": false,
            "start": "2018-04-20T00:00:00+0200",
            "end": "2018-04-22T00:00:00+0200",
            "date_interval_days": 1,
            "full_time": true
        },
        "start": "2018-04-20",
        "end": "2018-04-22",
        "color": "rgba(135,1,101,.8)"
    },
    {
        "id": "3",
        "title": "Test 2 Termin",
        "date_time": {
            "date": "22.04.",
            "time": false,
            "start": "2018-04-22T00:00:00+0200",
            "end": "2018-04-23T00:00:00+0200",
            "date_interval_days": 0,
            "full_time": true
        },
        "start": "2018-04-22",
        "end": "2018-04-23",
        "color": "#2BBBAD"
    },
    {
        "id": "2",
        "title": "Termin Test",
        "date_time": {
            "date": "23.04.",
            "time": false,
            "start": "2018-04-23T00:00:00+0200",
            "end": "2018-04-24T00:00:00+0200",
            "date_interval_days": 0,
            "full_time": true
        },
        "start": "2018-04-23",
        "end": "2018-04-24",
        "color": "rgba(135,1,101,.8)"
    },
    {
        "id": "4",
        "title": "Termin Test 1",
        "date_time": {
            "date": "25.04.",
            "time": "03:30 - 17:15",
            "start": "2018-04-25T03:30:00+0200",
            "end": "2018-04-25T17:15:00+0200",
            "date_interval_days": 0,
            "full_time": false
        },
        "start": "2018-04-25T03:30:00",
        "end": "2018-04-25T17:15:00",
        "color": "rgba(135,1,101,.8)"
    } 
]```

485fac5212770b72e8c1afd8f5838a2520567dea

**Comment by alexplusde** [comment]
Danke!
