### ISSUE TITLE
DEMO-Code für einzelnen Eintrag verbessern

### ISSUE THREAD

**Issue by steri-rex** [FriendsOfREDAXO/sked#62]
`$entries = \Sked\Handler\SkedHandler::getEntry($id); 
foreach ($entries as $data) {
   //dump($data);    
   $event                 = $data['entry'];
echo '<div class="entry_id"> ID: ' . $event->entry_id . ' </div>';  
} `
liefert die Fehlermeldung "Cannot use object of type stdClass as array"

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/sked/issues/63
