### ISSUE TITLE
kalenderblatt 

### ISSUE THREAD

**Issue by fw-thomas** [FriendsOfREDAXO/sked#69]
hallo zusammen,
die Termine werden ja als Liste ausdgegeben, was zum teil auch gut ist. 
Nun würde ich gerne einige Termine in einen Kalenderblatt ausgeben wollen. 

Hat jemand da schon was gebaut?? 

gruß thomas

**Comment by skerbis** [comment]
Duplicate of https://github.com/FriendsOfREDAXO/sked/issues/23
