### ISSUE TITLE
Feature: Termin duplizieren

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/sked#70]

**Comment by joachimdoerr** [comment]
Sollte man den duplizierten Termin kennzeichnen im Title also wenn ich den Termin mit den Namen `Termin` duplizieren täte dann würde das Duplikat so benannt `Termin [Duplikat]`

**Comment by joachimdoerr** [comment]
done. 8275fae4ad9e6881f93c6f94d1a55e2e4d2899f2
