### ISSUE TITLE
Farben nur als Hex Werte möglich

### ISSUE THREAD

**Issue by dtpop** [FriendsOfREDAXO/sked#75]
Der geniale Colorpicker mag keine Farben als rgb, da die Attribute per Komma getrennt sind. Mir ist noch keine Lösung eingefallen, wie man das sinnvoll umbauen kann und gleichzeitig kompatibel zu bestehenden Installationen bleiben kann. Vielleicht hat ja jemand eine Idee.

**Comment by joachimdoerr** [comment]
Ist rgb wirklich nötig?

**Comment by joachimdoerr** [comment]
läuft nun:

137e8500166d3e871b6430a99c4c7cfdd5b88d7e
c14c49eab83da5a821927855ed2b22732d1e5935

einfach unter settings rgb() oder rgba() Farben definieren z.b. `rgba(135,1,101,.8)` 

![bildschirmfoto 2018-04-20 um 10 56 31](https://user-images.githubusercontent.com/1191549/39041695-8727e5ea-4489-11e8-91df-6f9c6e9e2503.png)

**Comment by joachimdoerr** [comment]
Beispiel color wurde noch hinzugefügt 577f0b6f81765c76889bf787e1e6a62962dffe3c

**Comment by dtpop** [comment]
Danke!
