### ISSUE TITLE
fields defintion - attribute class wird bei textarea nicht richtig erzeugt

### ISSUE THREAD

**Issue by steri-rex** [FriendsOfREDAXO/sked#79]
```fields:
 - name: 'seminarkosten'
   type: 'textarea'
   label_de: 'Seminarkosten'
   label_en: 'Seminarkosten'
   attribute:
     - class: 'redactorEditor2-default'
```
ergibt

`<textarea id="rex-sked-entries-84c6be9aa79a5743e42020907e5e624c-seminarkosten" class="form-control" rows="6" name="84c6be9aa79a5743e42020907e5e624c[seminarkosten]">|redactorEditor2-default|</textarea>`

**Comment by skerbis** [comment]
kann ich bestätigen. Die Attribute werden nicht übernommen

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/sked/pull/80
