### ISSUE TITLE
Error: Unauthorized

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/sked#83]
Dieser Fehler tritt bei unterschiedlichen Installationen auf

> [Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (index.php, line 0)

> http://domain.de/index.php?rex-api-call=sked_exchange&start=2018-04-30&end=2018-06-11

<img width="813" alt="bildschirmfoto 2018-05-26 um 01 12 30" src="https://user-images.githubusercontent.com/791247/40569493-576b8e0a-6082-11e8-9259-4119f9b85b05.png">

**Comment by joachimdoerr** [comment]
das liegt am token der im backend generiert wird aber im frontend nicht verfügbar ist - der call aus dem assets des js callt ja aus dem frontend heraus

**Comment by joachimdoerr** [comment]
fürs erste gefixt, token check wurde jetzt erstmal entfernt, wir sollten da ein API token nutzen also der im Addon erzeugt und gespeichert wird und dann auch für extern vergeben werden kann.

b475f7ee72f6f686a06621ac0221aabc6bfcb46c
