### ISSUE TITLE
Kategorien in Kalender umbenennen?

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/sked#89]
https://github.com/FriendsOfREDAXO/sked/issues/57#issuecomment-398662164

**Comment by skerbis** [comment]
Oder einfach klarstellen, dass die Kategorien eben unterschiedliche Kalender sind?

**Comment by joachimdoerr** [comment]
ja das wird sich auswirken aber es würde schon sinn machen.

**Comment by skerbis** [comment]
Alternativ nur das Wording in den Lang-Dateien ändern?

**Comment by skerbis** [comment]
na ja... es ist halt schon im Einsatz und wenn sich die API plötzlich ändert ... hmmm

**Comment by joachimdoerr** [comment]
für jetzt einfach mit naming für später dann z.b. für ein major release dann richtig.

**Comment by skerbis** [comment]
lassen wir erstmal wie's ist. Das wording scheint kaum Probleme zu bereiten.
