### ISSUE TITLE
Watson-Integration

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/sked#90]
Siehe https://github.com/tbaddade/redaxo_watson/issues/31

**Comment by skerbis** [comment]
Ist in Arbeit

**Comment by skerbis** [comment]
@alexplusde hast du Lust ? Ein Beispiel findest du in feeds

**Comment by alexplusde** [comment]
Lust immer, aber ich bin an zu vielen anderen Sachen dran. Und watson funktioniert bei mir oft nicht mehr.

**Comment by skerbis** [comment]
? Welches Problem hast du mit Watson?

**Comment by alexplusde** [comment]
-> Slack

**Comment by skerbis** [comment]
@alexplusde 
https://github.com/FriendsOfREDAXO/sked/commit/2d33594ba97fd7cb84755ab6b60ccfc7ab634bd0

**Comment by skerbis** [comment]
<img width="960" alt="Bildschirmfoto 2020-03-29 um 14 27 25" src="https://user-images.githubusercontent.com/791247/77849288-e060e380-71ca-11ea-822c-1eae1d7b3eda.png">
