### ISSUE TITLE
Speichern ohne Angabe eine Datums möglich

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/sked#91]

**Comment by joachimdoerr** [comment]
Wünschst du dir das es möglich ist oder ist es möglich und es sollte nicht möglich sein?

**Comment by olien** [comment]
Es ist möglich und sollte eigentlich nicht so sein. bzw. sollte es zumindest nicht zu fehlern führen (wenn der Termin wiederholt wird)

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/sked/commit/4c4fbcd992fabda4fc1f7e0468f6da1109829303
