### ISSUE TITLE
Doku-Plugin: main_intro.md Verbesserungsvorschlag

### ISSUE THREAD

**Issue by christophboecker** [FriendsOfREDAXO/sked#92]
Hi Franziska,

ich hatte die Doku als Testobjekt benutzt und mich gewundert, warum der Rex bei mir nicht angezeigt wurde. Der Grund ist, wie ich dann festgestellt habe, eine leicht abweichende Konfiguration bei meinem Markdown-Parser.

Das hatte zur Folge, dass Dein Code in normalen Plugin-Kontext
```
<p style="text-align:center">
![FriendsOfREDAXO](for.png)
</p>
```
als drei unabhängige Zeilen geparst wird. Daher erkennt der Parser `![FriendsOfREDAXO](for.png)` und baut einen korrekten Image-Tag auf. Bei mir wurde den P-Block als ein Block betrachtet und `![FriendsOfREDAXO](for.png)` blieb ungeparst. Zufallsfund.

Das hat mich suchen lassen, wie man mit reinem Markdown-Mitteln den Rex mittig kriegen könnte. Es geht indem man eine geeeignete Klasse dahinter setzt.

```
![FriendsOfREDAXO](for.png){.center-block}
```

Nur mal so als Info.

Grüße
Chris

**Comment by skerbis** [comment]
@christophboecker ist eher ein Thema für das Demo-AddOn, da kommt es her.
