### ISSUE TITLE
Probleme und Vorschläge 

### ISSUE THREAD

**Issue by simonsinus** [FriendsOfREDAXO/sked#93]
Hallo,

ich finde es ganz toll, dass es dieses Kalender Addon gibt.

Ich habe noch ein paar Vorschläge:

- Manchmal ist die Termineingabe im Backend (zumindest unter Safari)
   etwas buggy und die Popup Datums-Auwahl funktioniert nicht immer
   zufriedenstellend. Also das sollte man beheben und sauber umsetzen.

- Es wäre im Backend auch schön mehrere Termine per Checkbox auszuwählen
   und dann verschiedene Aktionen, wie löschen usw. durchzuführen.

- Ein iCal Export wäre auch schön. Auch wenn ich das selbst hinbekäme.

Ansonsten finde ich das ein tolles Tool mit viel Potential.

**Comment by joachimdoerr** [comment]
Danke fürs Feedback.
* Betreffend Safari -> bei welchen Szenarien genau funktioniert die Datumsauswahl nicht?
* Staffelbearbeitung ist momentan nicht geplant aber wir können das gerne als Issue in die Wunschliste packen.
* Der Kalender Import/Export ist hingegen geplant nur mangels Ressourcen noch nicht realisiert worden.

**Comment by skerbis** [comment]
Dieses issue spricht mehre bekannte issues an - daher close
