### ISSUE TITLE
Bei regelmäßigen Terminen Ausnahmen erlauben

### ISSUE THREAD

**Issue by claudihey** [FriendsOfREDAXO/sked#95]
Was für ein tolles Addon! Ich bin gerade schwer begeistert!

Wäre es möglich, Ausnahmen bei regelmäßigen Terminen zu erlauben? 
Ich betreue einen Verein, bei dem z.B. immer Donnerstags eine Veranstaltung stattfindet. Durch die Ferien gibt es da aber immer Ausnahmen. Ist sowas realisierbar?

**Comment by joachimdoerr** [comment]
Ja kann man sicher umsetzen, hier müsste es dann eine Art "Gegenkalender" geben der die sich wiederholenden Termine außer kraft setzt.

**Comment by skerbis** [comment]
Ist eine sehr aufwendige Sache.
