### ISSUE TITLE
Ausdruck der Kalenderdarstellung ermöglichen

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/sked#97]

**Comment by skerbis** [comment]
wie stellst du Dir das vor? … Das Kalenderblatt oder die Liste?

**Comment by olien** [comment]
am liebsten natürlich beides.

könnt mir vorstellen, dass das kalenderblatt ausgedruckt und an irgendeiner wand gepinnt wird...

**Comment by skerbis** [comment]
gut, das würde ich dann aber individuell bauen evtl. direkt im Frontend

**Comment by javanita** [comment]
es wurde auch der Wunsch geäussert, einen Ausdruck im backend zu machen

**Comment by skerbis** [comment]
Hmm … evtl. ein PDF-Export. Wer möchte sich dran wagen. Könnte man gut mit pdfout realisieren.

**Comment by javanita** [comment]
wenn es nicht eilt, würde ich es gern versuchen

**Comment by skerbis** [comment]
Gerne :-)

**Comment by skerbis** [comment]
Wer was hat gerne PR ... vorerst close
