### ISSUE TITLE
JS-Fehler:  ReferenceError: trigger is not defined

### ISSUE THREAD

**Issue by DanielWeitenauer** [FriendsOfREDAXO/sked#99]
Beim Klick ins Textfeld vom Feld "Farbe" beim Editieren einer Kategorie, gebt es den JS-Fehler `ReferenceError: trigger is not defined`, was wohl an dieser Zeile liegt: https://github.com/FriendsOfREDAXO/sked/blob/master/assets/sked.js#L452

**Comment by joachimdoerr** [comment]
a2ca8e1f8dbdbeee39287a99dd4f181f94fabf12
